/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat;

import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author SUMIT
 */
public class serve extends javax.swing.JFrame implements Runnable
{

    
    static int i = 0;
 Thread T[] = new Thread[10];
      static String serveraddress =null;
	  static int port = 0;
	  static String username =null;
	  static ServerSocket serverSocket;
      private Socket socket= null;
      private DataInputStream streamIn =null;
    public serve() {
        initComponents();
        
        mainserver.setVisible(false);
	 mainlogin.setVisible(true);
     loginpanel2.setVisible(false);
     disconnect.setVisible(false);
     
     loginbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbutton1ActionPerformed(evt);
            }
        });
       disconnectbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               disconnectbuttonActionPerformed(evt);
            }
        });
        connectbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectbuttonActionPerformed(evt);
            }
        });
        loginbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbutton2ActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        mainlogin = new javax.swing.JPanel();
        mainserverpanel = new javax.swing.JLabel();
        loginpanel = new javax.swing.JPanel();
        loginpanel2 = new javax.swing.JPanel();
        mainloginpassword = new javax.swing.JLabel();
        loginbutton2 = new javax.swing.JButton();
        twolevelsecurity = new javax.swing.JLabel();
        mainpassword1text = new javax.swing.JPasswordField();
        loginpanel1 = new javax.swing.JPanel();
        mainloginuser1 = new javax.swing.JLabel();
        mainlogintext1 = new javax.swing.JTextField();
        mainloginpassword1 = new javax.swing.JLabel();
        loginbutton1 = new javax.swing.JButton();
        mainpassword1text1 = new javax.swing.JPasswordField();
        mainserver = new javax.swing.JPanel();
        servertop = new javax.swing.JPanel();
        datelabel = new javax.swing.JLabel();
        chatserver = new javax.swing.JLabel();
        clock = new javax.swing.JLabel();
        admin = new javax.swing.JButton();
        connection = new javax.swing.JPanel();
        connect = new javax.swing.JPanel();
        connectserver = new javax.swing.JLabel();
        connectservertext = new javax.swing.JTextField();
        connectport = new javax.swing.JLabel();
        connectporttext = new javax.swing.JTextField();
        connectbutton = new javax.swing.JButton();
        disconnect = new javax.swing.JPanel();
        disconnectserver = new javax.swing.JLabel();
        disconnectservertext = new javax.swing.JLabel();
        disconnectporttext = new javax.swing.JLabel();
        disconnectport = new javax.swing.JLabel();
        disconnectbutton = new javax.swing.JButton();
        status = new javax.swing.JPanel();
        onlineuser = new javax.swing.JLabel();
        activeuser = new javax.swing.JPanel();
        users = new javax.swing.JPanel();
        msgbox = new javax.swing.JTextField();
        sendbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chathistory = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainpanel.setBackground(new java.awt.Color(204, 204, 255));
        mainpanel.setPreferredSize(new java.awt.Dimension(793, 592));

        mainlogin.setBackground(new java.awt.Color(204, 204, 255));

        mainserverpanel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mainserverpanel.setText("  welcome main server login panel ");

        loginpanel.setBackground(new java.awt.Color(204, 204, 255));
        loginpanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        loginpanel2.setBackground(new java.awt.Color(204, 204, 255));
        loginpanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mainloginpassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mainloginpassword.setText("Password :");

        loginbutton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginbutton2.setText("Login");

        twolevelsecurity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        twolevelsecurity.setText(" confirm login access password 2");

        javax.swing.GroupLayout loginpanel2Layout = new javax.swing.GroupLayout(loginpanel2);
        loginpanel2.setLayout(loginpanel2Layout);
        loginpanel2Layout.setHorizontalGroup(
            loginpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(loginpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginpanel2Layout.createSequentialGroup()
                        .addComponent(mainloginpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(twolevelsecurity, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainpassword1text, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginpanel2Layout.createSequentialGroup()
                        .addComponent(loginbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))))
        );
        loginpanel2Layout.setVerticalGroup(
            loginpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(twolevelsecurity, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(loginpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainloginpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainpassword1text, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(loginbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        loginpanel1.setBackground(new java.awt.Color(204, 204, 255));
        loginpanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mainloginuser1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mainloginuser1.setText("user name :");

        mainlogintext1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        mainloginpassword1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mainloginpassword1.setText("Password :");

        loginbutton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginbutton1.setText("Login");

        javax.swing.GroupLayout loginpanel1Layout = new javax.swing.GroupLayout(loginpanel1);
        loginpanel1.setLayout(loginpanel1Layout);
        loginpanel1Layout.setHorizontalGroup(
            loginpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(loginpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainloginuser1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainloginpassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainlogintext1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(mainpassword1text1))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        loginpanel1Layout.setVerticalGroup(
            loginpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(loginpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainloginuser1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainlogintext1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(loginpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainloginpassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainpassword1text1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(loginbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout loginpanelLayout = new javax.swing.GroupLayout(loginpanel);
        loginpanel.setLayout(loginpanelLayout);
        loginpanelLayout.setHorizontalGroup(
            loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
            .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(loginpanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loginpanelLayout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(loginpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(2, 2, 2)))
        );
        loginpanelLayout.setVerticalGroup(
            loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
            .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(loginpanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loginpanelLayout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(loginpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(2, 2, 2)))
        );

        javax.swing.GroupLayout mainloginLayout = new javax.swing.GroupLayout(mainlogin);
        mainlogin.setLayout(mainloginLayout);
        mainloginLayout.setHorizontalGroup(
            mainloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainloginLayout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(mainserverpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addGroup(mainloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainloginLayout.createSequentialGroup()
                    .addContainerGap(204, Short.MAX_VALUE)
                    .addComponent(loginpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(179, 179, 179)))
        );
        mainloginLayout.setVerticalGroup(
            mainloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainloginLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(mainserverpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(442, Short.MAX_VALUE))
            .addGroup(mainloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainloginLayout.createSequentialGroup()
                    .addContainerGap(150, Short.MAX_VALUE)
                    .addComponent(loginpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(85, 85, 85)))
        );

        mainserver.setBackground(new java.awt.Color(204, 204, 255));
        mainserver.setPreferredSize(new java.awt.Dimension(793, 579));

        servertop.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        datelabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        chatserver.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chatserver.setText("  main  chat server ");

        clock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        admin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        admin.setText("Admin");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout servertopLayout = new javax.swing.GroupLayout(servertop);
        servertop.setLayout(servertopLayout);
        servertopLayout.setHorizontalGroup(
            servertopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, servertopLayout.createSequentialGroup()
                .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(chatserver)
                .addGap(65, 65, 65)
                .addComponent(datelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        servertopLayout.setVerticalGroup(
            servertopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatserver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(datelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(clock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(admin, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        connection.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        connection.setPreferredSize(new java.awt.Dimension(771, 165));

        connect.setPreferredSize(new java.awt.Dimension(771, 165));

        connectserver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        connectserver.setText("server :");

        connectservertext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        connectservertext.setText("127.0.0.1");
        connectservertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectservertextActionPerformed(evt);
            }
        });

        connectport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        connectport.setText("port:");

        connectporttext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        connectporttext.setText("14001");

        connectbutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        connectbutton.setText("connect");

        javax.swing.GroupLayout connectLayout = new javax.swing.GroupLayout(connect);
        connect.setLayout(connectLayout);
        connectLayout.setHorizontalGroup(
            connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(connectserver)
                .addGap(18, 18, 18)
                .addComponent(connectservertext, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(connectport, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connectporttext, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(connectbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        connectLayout.setVerticalGroup(
            connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connectserver, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connectservertext, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connectport, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connectporttext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connectbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        disconnect.setPreferredSize(new java.awt.Dimension(771, 165));

        disconnectserver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        disconnectserver.setText("connect at server");

        disconnectservertext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        disconnectservertext.setText("127.0.0.1");

        disconnectporttext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        disconnectporttext.setText("8080");

        disconnectport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        disconnectport.setText("port");

        disconnectbutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        disconnectbutton.setText("disconnect");

        javax.swing.GroupLayout disconnectLayout = new javax.swing.GroupLayout(disconnect);
        disconnect.setLayout(disconnectLayout);
        disconnectLayout.setHorizontalGroup(
            disconnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disconnectLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(disconnectserver, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(disconnectservertext, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(disconnectport, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disconnectporttext, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(disconnectbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        disconnectLayout.setVerticalGroup(
            disconnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disconnectLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(disconnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disconnectserver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disconnectservertext, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disconnectporttext, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disconnectport, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disconnectbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout connectionLayout = new javax.swing.GroupLayout(connection);
        connection.setLayout(connectionLayout);
        connectionLayout.setHorizontalGroup(
            connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(disconnect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
            .addGroup(connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(connectionLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(connect, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        connectionLayout.setVerticalGroup(
            connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectionLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(connectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(connectionLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(connect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );

        status.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        status.setPreferredSize(new java.awt.Dimension(246, 380));

        onlineuser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        onlineuser.setText("                  online users ");

        activeuser.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout activeuserLayout = new javax.swing.GroupLayout(activeuser);
        activeuser.setLayout(activeuserLayout);
        activeuserLayout.setHorizontalGroup(
            activeuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        activeuserLayout.setVerticalGroup(
            activeuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout statusLayout = new javax.swing.GroupLayout(status);
        status.setLayout(statusLayout);
        statusLayout.setHorizontalGroup(
            statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(onlineuser, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
            .addComponent(activeuser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        statusLayout.setVerticalGroup(
            statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusLayout.createSequentialGroup()
                .addComponent(onlineuser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(activeuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        users.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sendbutton.setText("send");
        sendbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbuttonActionPerformed(evt);
            }
        });

        chathistory.setColumns(20);
        chathistory.setRows(5);
        jScrollPane1.setViewportView(chathistory);

        javax.swing.GroupLayout usersLayout = new javax.swing.GroupLayout(users);
        users.setLayout(usersLayout);
        usersLayout.setHorizontalGroup(
            usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersLayout.createSequentialGroup()
                .addComponent(msgbox, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(sendbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        usersLayout.setVerticalGroup(
            usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msgbox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout mainserverLayout = new javax.swing.GroupLayout(mainserver);
        mainserver.setLayout(mainserverLayout);
        mainserverLayout.setHorizontalGroup(
            mainserverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(servertop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(connection, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainserverLayout.createSequentialGroup()
                .addComponent(users, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainserverLayout.setVerticalGroup(
            mainserverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainserverLayout.createSequentialGroup()
                .addComponent(servertop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(connection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(mainserverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(users, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
            .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainpanelLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(mainlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainpanelLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(mainserver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
            .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainpanelLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(mainlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainpanelLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(mainserver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbuttonActionPerformed
        // TODO add your handling code here:
        String msg = msgbox.getText();  
   	     
		 try{
			System.out.println("\nserver is writting \n");
            OutputStream os = socket.getOutputStream();
            OutputStreamWriter osw = new OutputStreamWriter(os);
            BufferedWriter bw = new BufferedWriter(osw);
            String sendMessage = msg + "\n";
            bw.write(sendMessage);
            bw.flush();
            System.out.println("msg = "+msg);
            chathistory.append(sendMessage+"\n");			
		 }
	  catch(Exception e)
	  {
		  System.out.println("msg not send");
		  
	  }
    }//GEN-LAST:event_sendbuttonActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
        new registration().setVisible(true);
    }//GEN-LAST:event_adminActionPerformed

    private void connectservertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectservertextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connectservertextActionPerformed

     private void loginbutton1ActionPerformed(java.awt.event.ActionEvent evt)
      {
          date d = new date();
          datelabel.setText(d.todaydate());
          currenttime tm = new currenttime();
          Thread tt = new Thread(){
              public void run()
              {
             while(true)
               {
                 try
                   {
                     Thread.currentThread().sleep(100); 
                     clock.setText(tm.updatetime());
                   }catch(Exception e)
                      {}
              }}};
          tt.start();
          username= mainlogintext1.getText();
          String password1 = new String(mainpassword1text1.getPassword());
          serverlogin1 sl1 = new serverlogin1(username,password1);
          String s = sl1.reply();
	  if(s.equals(password1))
	      	{
                    JOptionPane.showMessageDialog(null,"correct user and passward");
		    loginpanel2.setVisible(true);
                    loginpanel1.setVisible(false);
		}
       	 else 
		{
		    JOptionPane.showMessageDialog(null,"Wrong Password / Username");
                    mainlogintext1.setText("");
                    mainpassword1text1.setText("");                  
		}     
      }   
	  private void loginbutton2ActionPerformed(java.awt.event.ActionEvent evt)
      {
          String password = new String(mainpassword1text.getPassword());   
          serverlogin2 sl2=new serverlogin2(username,password);
          String s =sl2.reply();
          if(s.equals(password))
	     	{
                  JOptionPane.showMessageDialog(null,"login sucessfull");
		  loginpanel1.setVisible(false);
                  loginpanel.setVisible(false);
                  mainlogin.setVisible(false);
                  mainserver.setVisible(true);
	        }
          else 
		{
	          JOptionPane.showMessageDialog(null,"Wrong Password / Username");
                  mainlogintext1.setText("");
                  mainpassword1text1.setText("");                  
		} 
                     
      }
	 public  void run()
	{   
	   String a = "users";
	   String c = "messagesend";
	   String b = "messagerecieve";
	   System.out.println("server side main thread name is :"+Thread.currentThread().getName());
	   if(a.equals(Thread.currentThread().getName()))
	   {
		   while(true)
		   {
		   try{
		        System.out.println("waiting for client");
		        socket = serverSocket.accept();
		        System.out.println("client connected");
    	      T[i]=new Thread(){public void run()
	                 {
						 System.out.println("server side thread name is :"+Thread.currentThread().getName());
					while(true)	{
                     try{
         		           InputStream is = socket.getInputStream();
                           InputStreamReader isr = new InputStreamReader(is);
                           BufferedReader br = new BufferedReader(isr);
                           String number = br.readLine();
                           System.out.println("Message received from client is "+number);
				           chathistory.append(number+"\n");
			           }catch(Exception x){
				         System.out.println("something error");
					}
					}
			  }};
			  T[i].start();
 		      i++;
			  }
		   catch(Exception x)
		     {}
	   }}
	   else
	   { 
          
       }}
      private void connectbuttonActionPerformed(java.awt.event.ActionEvent evt)
      {	  
	    port = Integer.parseInt(connectporttext.getText());
		serveraddress = connectservertext.getText();
		disconnectservertext.setText(serveraddress);
		disconnectporttext.setText(Integer.toString(port));
		connect.setVisible(false);
        disconnect.setVisible(true);
		try
		{
		 serverSocket = new ServerSocket(port);  
         System.out.println("Server started: " + serverSocket);
		}
		  catch(IOException e)
	     {
		  System.out.println("error h");
	     }
	     Thread t1 = new Thread(this);
		 t1.setName("users");
	     t1.start();
		
		}
      private void disconnectbuttonActionPerformed(java.awt.event.ActionEvent evt)
      {
         connect.setVisible(true);
         disconnect.setVisible(false);
      }
	 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(serve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(serve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(serve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(serve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new serve().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel activeuser;
    private javax.swing.JButton admin;
    private javax.swing.JTextArea chathistory;
    private javax.swing.JLabel chatserver;
    private javax.swing.JLabel clock;
    private javax.swing.JPanel connect;
    private javax.swing.JButton connectbutton;
    private javax.swing.JPanel connection;
    private javax.swing.JLabel connectport;
    private javax.swing.JTextField connectporttext;
    private javax.swing.JLabel connectserver;
    private javax.swing.JTextField connectservertext;
    private javax.swing.JLabel datelabel;
    private javax.swing.JPanel disconnect;
    private javax.swing.JButton disconnectbutton;
    private javax.swing.JLabel disconnectport;
    private javax.swing.JLabel disconnectporttext;
    private javax.swing.JLabel disconnectserver;
    private javax.swing.JLabel disconnectservertext;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginbutton1;
    private javax.swing.JButton loginbutton2;
    private javax.swing.JPanel loginpanel;
    private javax.swing.JPanel loginpanel1;
    private javax.swing.JPanel loginpanel2;
    private javax.swing.JPanel mainlogin;
    private javax.swing.JLabel mainloginpassword;
    private javax.swing.JLabel mainloginpassword1;
    private javax.swing.JTextField mainlogintext1;
    private javax.swing.JLabel mainloginuser1;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPasswordField mainpassword1text;
    private javax.swing.JPasswordField mainpassword1text1;
    private javax.swing.JPanel mainserver;
    private javax.swing.JLabel mainserverpanel;
    private javax.swing.JTextField msgbox;
    private javax.swing.JLabel onlineuser;
    private javax.swing.JButton sendbutton;
    private javax.swing.JPanel servertop;
    private javax.swing.JPanel status;
    private javax.swing.JLabel twolevelsecurity;
    private javax.swing.JPanel users;
    // End of variables declaration//GEN-END:variables
}
